
CREATE OR REPLACE FUNCTION get_first_name_by_id (in_id BIGINT) RETURNS VARCHAR(60)
    AS 'SELECT first_name FROM SINGER WHERE id = $1;'
    LANGUAGE SQL
    IMMUTABLE
    RETURNS NULL ON NULL INPUT;